pipeline{
    agent {label 'master'}
    stages {
        stage('Build'){
            parallel{
                stage('r1.0'){
                    agent {label 'master'}
                    steps {
                        sh 'pwd'
                        sh 'ls'
                    }
                }
                stage('r1.1'){
                    agent {label 'master'}
                    steps {
                        sh 'pwd'
                        sh 'ls'
                    }
                }
            }
		}
	}
}
